### ISSUE TITLE
Wrong link to repository in project docs

### ISSUE THREAD

**Issue by LonelyPrincess** [guidesmiths/swagger-endpoint-validator#20]
The URL included at the top right side of the `docsify` generated page is wrong: it links to a non-existant address rather than to the actual repository.

```
https://github.com/git@github.com:guidesmiths/swagger-endpoint-validator
```

![image](https://user-images.githubusercontent.com/17673317/81043878-1456b500-8eab-11ea-9bdb-ae4ed66c03ba.png)

### How to fix

This issue can be easily solved by adding the right value to the [`repo` property in the `docsify` settings](https://docsify.js.org/#/configuration?id=repo) declared in the [`index.html` file](https://github.com/guidesmiths/swagger-endpoint-validator/blob/master/docs/index.html):

```
window.$docsify = {
  name: 'swagger-endpoint-validator',
  themeColor: '#17ae8e',
  repo: 'git@github.com:guidesmiths/swagger-endpoint-validator'
}
```

For things to work, we must replace the current `repo` value to either `guidesmiths/swagger-endpoint-validator` or the actual [URL to the repository in GitHub](https://github.com/guidesmiths/swagger-endpoint-validator).

**Comment by UlisesGascon** [comment]
Thanks for bring this @LonelyPrincess! Do you want to create a PR to fix it? :-)
